name: gloomhaven_enhancement_calc
description: Character sheet and enhancement calculator

version: 4.3.2+322

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.4
  auto_size_text: ^3.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  flutter_svg: ^2.2.3
  share_plus: ^12.0.0
  file_picker: ^10.1.9
  intl: any
  smooth_page_indicator: ^2.0.1
  permission_handler: ^12.0.0
  # problems?
  uuid: ^4.2.1
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  url_launcher: ^6.2.1
  faker: ^2.2.0
  path: ^1.8.3
  # maybe URL launcher is problematic
  font_awesome_flutter: ^10.6.0
  material_design_icons_flutter: ^7.0.7296
  collection: ^1.19.0
  device_region: ^1.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons: # dart run flutter_launcher_icons
  android: true
  ios: true
  image_path: "icons/launcher_icon.png"
  image_path_android: "icons/android/launcher_icon.png"
  adaptive_icon_background: "#262626"
  adaptive_icon_foreground: "icons/android/foreground.png"
  adaptive_icon_foreground_inset: 0
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    # - icons/
    # - icons/android/
    - images/
    - images/attack_modifiers/
    - images/class_icons/
    # - images/elements/
    - images/equipment_slots/
    - images/pips/
    - images/titles/
    - images/resources/
    # - images/status_effects/

  fonts:
    - family: PirataOne
      fonts:
        - asset: fonts/pirata_one.ttf
    - family: HighTower
      fonts:
        - asset: fonts/high_tower.ttf
    - family: Nyala
      fonts:
        - asset: fonts/nyala.ttf
    - family: Roboto
      fonts:
        - asset: fonts/roboto/Roboto-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/open_sans/OpenSans-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Regular.ttf
